name: video_editor
version: 2.4.0
publish_to: none
environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffmpeg_kit_flutter: ^5.1.0
  path: ^1.8.0 # update to `1.8.1` causes #79
  path_provider: ^2.0.12
  transparent_image: ^2.0.1 # show fade-in placeholder in thumbnails generation
  dio: ^4.0.6
  video_thumbnail: ^0.5.3
  better_player:
    git:
      url: git@github.com:captis/dart-packages.git
      ref: master
      path: video_player/better_player

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

screenshots:
  - description: "Video editor demo"
    path: assets/demo_thumb.webp
